Homework2
made-mlops-2022/gasanov_marat pull request #2
Opened 2022-11-24 10:24 UTC by gassannov

1. Оберните inference вашей модели в rest сервис на FastAPI, должен быть endpoint /predict (3 балла) +
2. Напишите endpoint /health, который должен возращать 200, если ваша модель готова к работе (такой чек особенно актуален, если делаете доп задание про скачивание из хранилища) (1 балл) +
3. Напишите unit тест для /predict (https://fastapi.tiangolo.com/tutorial/testing/, https://flask.palletsprojects.com/en/1.1.x/testing/) (3 балла) + 
4. Напишите скрипт, который будет делать запросы к вашему сервису (2 балла) + 
5. Напишите Dockerfile, соберите на его основе образ и запустите локально контейнер (docker build, docker run). Внутри контейнера должен запускаться сервис, написанный в предущем пункте. Закоммитьте его, напишите в README.md корректную команду сборки (4 балла)+
6. Опубликуйте образ в https://hub.docker.com/, используя docker push (вам потребуется зарегистрироваться) (2 балла) + 
7. Опишите в README.md корректные команды docker pull/run, которые должны привести к тому, что локально поднимется на inference ваша модель. Убедитесь, что вы можете протыкать его скриптом из пункта 3 (1 балл)+
8. Проведите самооценку - распишите в реквесте какие пункты выполнили и на сколько баллов, укажите общую сумму баллов (1 балл)+
Дополнительная часть:
1. Ваш сервис скачивает модель из S3 или любого другого хранилища при старте, путь для скачивания передается через переменные окружения (+2 доп балла) - 
2. Оптимизируйте размер docker image. Опишите в README.md, что вы предприняли для сокращения размера и каких результатов удалось добиться. Должно получиться мини исследование -- я сделал тото и получился такой-то результат (+2 доп балла) https://docs.docker.com/develop/develop-images/dockerfile_best-practices/ - 
3. Сделайте валидацию входных данных https://pydantic-docs.helpmanual.io/usage/validators/ . Например, порядок колонок не совпадает с трейном, типы, допустимые максимальные и минимальные значения. Проявите фантазию, это доп. баллы, проверка не должна быть тривиальной. Вы можете сохранить вместе с моделью доп информацию о структуре входных данных, если это нужно (+2 доп балла). https://fastapi.tiangolo.com/tutorial/handling-errors/ -- возращайте 400, в случае, если валидация не пройдена +(простая валидация с помощью pydantic validator)
Итого выполнено:
Все пункуты базовой части + 3 пункт продвинутой

2022-12-08 21:42 UTC, SVizor42 commented on homework2/main.py
> +    print(input_item)
Нужно использовать логирование

2022-12-08 21:46 UTC, SVizor42 commented on homework2/request_script.py
> +    # print(f'health responce = {response.json()}')
Нужно убрать закомментированные участки кода

2022-12-08 21:53 UTC, SVizor42 commented on homework2/queries.py
> +        return int(f.read()[5])
Для чего здесь эта работа с файлами? Нам достаточно просто возвращать прогноз

2022-12-09 09:35 UTC, SVizor42 requested changes
Нужно посмотреть комментарии выше.

Плюс:
1. После запуска Docker контейнера не удается получить доступ как к эндпойнту  /health, так и к /predict. Нужно проверить этот момент.
2. Скрипт, который отправляет запросы к сервису, должен запускаться извне, а не из контейнера. В этом то его суть: он должен уметь достучаться до сервиса в независимости от того, где и как он запущен - в среде разработки, в контейнере, в облаке и т.д.

Возвращаю на доработку.

2022-12-18 08:59 UTC, gassannov commented
исправил замечания.

2022-12-18 09:00 UTC, gassannov commented
насчет работы с файлами. это такой костыль, потому что predict из дз1, не возвращает предсказанное значение, а записывает в файл, поэтому пришлось прикрутить работу с файлами.

2022-12-18 16:05 UTC, SVizor42 commented on homework2/request_script.py
> +    print(f'health responce = {response.json()}')
Используй логирование плиз, нужно избегать принтов в проде

2022-12-18 16:06 UTC, SVizor42 commented on homework2/main.py
> +import logging
Стандартные модули импортируются до локальных

2022-12-18 16:07 UTC, SVizor42 approved these changes
Хорошо, принято.

**Сумма: 19 баллов**

Ветку можно сливать.

2022-12-18 21:28 UTC, merged